name: Scheduled Data Fetch

on:
  schedule:
    - cron: '*/6 * * * *'

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run script
      run: bash update.sh

    # https://github.com/peaceiris/actions-gh-pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        external_repository: noricha-vr/vrc-ta-hub-json
        publish_branch: gh-pages
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        publish_dir: ./docs
